site_name: SeFuSe Documentation
theme:
  name: material

nav:
  - Home: README.md
  - Data Processing Module:
      - Config: data_processing/config/config.md
      - Processing:
          - Cleaner: data_processing/processing/cleaner.md
          - UUID Generator: data_processing/processing/uuid_generator.md
          - Value Extractor: data_processing/processing/value_extractor.md
      - Utils:
          - Downloading: data_processing/utils/downloading.md
          - Extractor: data_processing/utils/extractor.md
      - Main Workflow: data_processing/main.md
  - FastAPI Module:
      - FastAPI Utils: fastapi/utils/fastapi_utils.md
      - Qdrant Utils: fastapi/utils/qdrant_utils.md
      - Main App: fastapi/main.md
  - Streamlit Module:
      - Utils: streamlit/utils/utils.md
      - Main Application: streamlit/app.md

markdown_extensions:
  - attr_list
  - md_in_html
